export const ALL_ROOMS_SUCCESS = 'ALL_ROOMS_SUCCESS';
export const ALL_ROOMS_FAIL = 'ALL_ROOMS_FAIL';

export const ROOM_DETAILS_SUCCESS = 'ROOM_DETAILS_SUCCESS';
export const ROOM_DETAILS_FAIL = 'ROOM_DETAILS_FAIL';

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST';
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS';

export const NEW_ROOM_REQUEST = 'NEW_ROOM_REQUEST';
export const NEW_ROOM_SUCCESS = 'NEW_ROOM_SUCCESS';

export const CLEAR_ALL_ROOMS_ERRORS = 'CLEAR_ALL_ROOMS_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

